.TH "HeroNode" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeroNode
.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні атрибути"

.in +1c
.ti -1c
.RI "string \fBdata\fP"
.br
.ti -1c
.RI "vector< string > \fBnames\fP"
.br
.ti -1c
.RI "multimap< int, string > \fBhb\fP"
.br
.ti -1c
.RI "int \fBid\fP = 0"
.br
.ti -1c
.RI "bool \fBway\fP"
.br
.ti -1c
.RI "\fBHeroNode\fP * \fBleft\fP"
.br
.ti -1c
.RI "\fBHeroNode\fP * \fBright\fP"
.br
.in -1c
.SS "Дружні класи"

.in +1c
.ti -1c
.RI "class \fBBinarySearchTree< string, HeroNode >\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
