.TH "HeroFunctions" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeroFunctions
.SH SYNOPSIS
.br
.PP
.PP
Успадковує клас \fBBinarySearchTree< string, HeroNode >\fP\&.
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBInFile\fP ()"
.br
.ti -1c
.RI "void \fBAddHero\fP ()"
.br
.ti -1c
.RI "void \fBDelete\fP ()"
.br
.ti -1c
.RI "void \fBPrintInOrder\fP ()"
.br
.ti -1c
.RI "void \fBFind\fP ()"
.br
.ti -1c
.RI "void \fBSeries\fP ()"
.br
.in -1c
.SS "Додаткові успадковані елементи"


.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
