.TH "TreeChildrenList< T, U >" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeChildrenList< T, U >
.SH SYNOPSIS
.br
.PP
.PP
Успадковано класами \fBFunctions< T, U >\fP\&.
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBAddLeaf\fP (T e, U *node)"
.br
.ti -1c
.RI "void \fBAddLeaf_v\fP (std::vector< T > v, U *node)"
.br
.ti -1c
.RI "U * \fBnewNode\fP (int data)"
.br
.ti -1c
.RI "void \fBRemoveNode\fP (U *p, U *parent, int a)"
.br
.ti -1c
.RI "void \fBRemoveNode_vect\fP (U *p, U *parent, int a)"
.br
.in -1c
.SS "Загальнодоступні атрибути"

.in +1c
.ti -1c
.RI "int \fBd\fP = 0"
.br
.ti -1c
.RI "U * \fBroot\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
