.TH "BinaryTree< T, U >" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryTree< T, U >
.SH SYNOPSIS
.br
.PP
.PP
Успадковано класами \fBFunctions< T, U >\fP\&.
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "U * \fBFind_smallest\fP ()"
.br
.ti -1c
.RI "U * \fBAddLeaf\fP (U *root, U *node)"
.br
.ti -1c
.RI "U * \fBAddLeaf_v\fP (U *root, U *node)"
.br
.ti -1c
.RI "void \fBRemoveNode\fP (U *p, U *parent, int a)"
.br
.ti -1c
.RI "void \fBRemoveNode_vect\fP (U *p, U *parent, int a)"
.br
.ti -1c
.RI "U * \fBcreat_leaf_v\fP (std::vector< T > v, bool way1)"
.br
.ti -1c
.RI "U * \fBcreat_leaf\fP (T e, bool way1)"
.br
.in -1c
.SS "Загальнодоступні атрибути"

.in +1c
.ti -1c
.RI "int \fBd\fP = 1"
.br
.ti -1c
.RI "U * \fBroot\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
