.TH "MainWindow" 3 "Пт 25 Июн 2021" "lab2 or 1 documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- The \fBMainWindow\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Базовые классы:QMainWindow\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
The \fBMainWindow\fP class\&. 
.SH "Конструктор(ы)"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fCnullptr\fP)"

.SS "MainWindow::~MainWindow ()"


.SH "Автор"
.PP 
Автоматически создано Doxygen для lab2 or 1 documentation из исходного текста\&.
