.TH "C:/Users/aDmin/Desktop/untitled/main.h" 3 "Пт 25 Июн 2021" "lab2 or 1 documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aDmin/Desktop/untitled/main.h
.SH SYNOPSIS
.br
.PP
\fC#include <QElapsedTimer>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QThread>\fP
.br
\fC#include <QRadioButton>\fP
.br

.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBMIN\fP   0"
.br
.ti -1c
.RI "#define \fBMAX\fP   99"
.br
.ti -1c
.RI "#define \fBSLEEP_ms\fP   500"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBdelay\fP ()"
.br
.RI "delay create dealy in the qt "
.ti -1c
.RI "void \fBupdateArray\fP (int data[], int length)"
.br
.RI "updateArray filling array with random numbers "
.ti -1c
.RI "void \fBhighlightButton\fP (QPushButton *button)"
.br
.RI "highlightButton set the background of button to yellow to attract view "
.ti -1c
.RI "void \fBunhighlightButton\fP (QPushButton *button)"
.br
.RI "unhighlightButton set the button to normal color "
.ti -1c
.RI "void \fBswap\fP (int *a, int *b)"
.br
.RI "swap swap value of a and b "
.ti -1c
.RI "void \fBsetButtonValue\fP (QPushButton *button, int data)"
.br
.RI "setButtonValue set button "
.ti -1c
.RI "void \fBbubbleSort\fP (QPushButton *button[], int data[], int length)"
.br
.RI "bubbleSort run selection sort algorith and update ui "
.ti -1c
.RI "void \fBselectionSort\fP (QPushButton *button[], int data[], int length)"
.br
.RI "selectionSort run selection sort algorith and update ui "
.ti -1c
.RI "void \fBupdateButton\fP (QPushButton *button[], int data[], int length)"
.br
.RI "updateButton "
.in -1c
.SH "Макросы"
.PP 
.SS "#define MAX   99"

.SS "#define MIN   0"

.SS "#define SLEEP_ms   500"

.SH "Функции"
.PP 
.SS "void bubbleSort (QPushButton * button[], int data[], int length)"

.PP
bubbleSort run selection sort algorith and update ui 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP - array to sort for ui 
.br
\fIdata\fP - array to sort 
.br
\fIlength\fP - of array 
.RE
.PP

.SS "void delay ()"

.PP
delay create dealy in the qt 
.SS "void highlightButton (QPushButton * button)"

.PP
highlightButton set the background of button to yellow to attract view 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP - active int 
.RE
.PP

.SS "void selectionSort (QPushButton * button[], int data[], int length)"

.PP
selectionSort run selection sort algorith and update ui 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP - array to sort for ui 
.br
\fIdata\fP - array to sort 
.br
\fIlength\fP - of array 
.RE
.PP

.SS "void setButtonValue (QPushButton * button, int data)"

.PP
setButtonValue set button 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP 
.br
\fIdata\fP 
.RE
.PP

.SS "void swap (int * a, int * b)"

.PP
swap swap value of a and b 
.PP
\fBАргументы\fP
.RS 4
\fIa\fP - int 
.br
\fIb\fP - int 
.RE
.PP

.SS "void unhighlightButton (QPushButton * button)"

.PP
unhighlightButton set the button to normal color 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP - not active now 
.RE
.PP

.SS "void updateArray (int data[], int length)"

.PP
updateArray filling array with random numbers 
.PP
\fBАргументы\fP
.RS 4
\fIdata\fP - array 
.br
\fIlength\fP - lenth of array 
.RE
.PP

.SS "void updateButton (QPushButton * button[], int data[], int length)"

.PP
updateButton 
.PP
\fBАргументы\fP
.RS 4
\fIbutton\fP - array to sort for ui 
.br
\fIdata\fP - array to sort 
.br
\fIlength\fP - of array 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для lab2 or 1 documentation из исходного текста\&.
