.TH "C:/Users/aDmin/Desktop/untitled/mainwindow.cpp" 3 "Пт 25 Июн 2021" "lab2 or 1 documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aDmin/Desktop/untitled/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для lab2 or 1 documentation из исходного текста\&.
