.TH "C:/Users/aDmin/Desktop/untitled/mainwindow.h" 3 "Пт 25 Июн 2021" "lab2 or 1 documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aDmin/Desktop/untitled/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "The \fBMainWindow\fP class\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для lab2 or 1 documentation из исходного текста\&.
