.TH "BookNode" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BookNode
.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні атрибути"

.in +1c
.ti -1c
.RI "\fBBookNode\fP * \fBleft\fP"
.br
.ti -1c
.RI "\fBBookNode\fP * \fBright\fP"
.br
.ti -1c
.RI "string \fBdata\fP"
.br
.ti -1c
.RI "vector< string > \fBauthors\fP"
.br
.ti -1c
.RI "int \fBd\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBpages\fP"
.br
.ti -1c
.RI "string \fBplot\fP"
.br
.ti -1c
.RI "int \fBid\fP = 0"
.br
.ti -1c
.RI "bool \fBway\fP"
.br
.in -1c
.SS "Дружні класи"

.in +1c
.ti -1c
.RI "class \fBBinarySearchTree< string, BookNode >\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
