.TH "Functions< T, U >" 3 "Понеділок, 2 листопада 2020" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Functions< T, U >
.SH SYNOPSIS
.br
.PP
.PP
Успадковує клас \fBBinarySearchTree< T, U >\fP, \fBBinaryTree< T, U >\fP і \fBTreeChildrenList< T, U >\fP\&.
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBFindByTheWay\fP (int a)"
.br
.ti -1c
.RI "void \fBDelete\fP (int a, int b)"
.br
.ti -1c
.RI "void \fBAddLeaf\fP (int a)"
.br
.ti -1c
.RI "void \fBAddLeaf_vect\fP (int a)"
.br
.ti -1c
.RI "void \fBFind\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintInOrder\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintInOrder_vect\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintPostOrder\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintPostOrder_vect\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintPreOrder\fP (int a)"
.br
.ti -1c
.RI "void \fBPrintPreOrder_vect\fP (int a)"
.br
.ti -1c
.RI "void \fBFind_vect\fP (int a)"
.br
.ti -1c
.RI "void \fBDelete_vect\fP (int a, int b)"
.br
.in -1c
.SS "Дружні класи"

.in +1c
.ti -1c
.RI "class \fBNode< T >\fP"
.br
.in -1c
.SS "Додаткові успадковані елементи"


.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Lab 1 з тексту програми\&.
